/*
 * generated by Xtext 2.11.0
 */
package de.wwu.pi.guidsl.ide

import com.google.inject.Guice
import de.wwu.pi.guidsl.GuiDslRuntimeModule
import de.wwu.pi.guidsl.GuiDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GuiDslIdeSetup extends GuiDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GuiDslRuntimeModule, new GuiDslIdeModule))
	}
	
}
