/*
 * generated by Xtext 2.11.0
 */
package de.wwu.pi.guidsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GuiDslStandaloneSetup extends GuiDslStandaloneSetupGenerated {

	def static void doSetup() {
		new GuiDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
